"""empty message

Revision ID: daaa0f24f35a
Revises: 
Create Date: 2018-08-12 14:20:17.100066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daaa0f24f35a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('num_of_games', sa.Integer(), nullable=True),
    sa.Column('rolls_per_game', sa.Integer(), nullable=True),
    sa.Column('bet_unit', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('games',
    sa.Column('_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('simulation_id', sa.Integer(), nullable=True),
    sa.Column('arrival_cash', sa.Integer(), nullable=True),
    sa.Column('minimum_bet', sa.Integer(), nullable=True),
    sa.Column('puck', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_table('bets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('point', sa.Integer(), nullable=True),
    sa.Column('working', sa.Boolean(), nullable=False),
    sa.Column('payout', sa.Integer(), nullable=True),
    sa.Column('settled', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games._id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rolls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('puck', sa.Integer(), nullable=True),
    sa.Column('die_one', sa.Integer(), nullable=True),
    sa.Column('die_two', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games._id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rolls')
    op.drop_table('bets')
    op.drop_table('games')
    op.drop_table('simulations')
    # ### end Alembic commands ###
